# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Budget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(822, 617)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame.setStyleSheet("QFrame{\n"
"background-image: url(:/newPrefix/مجلد جديد/360_F_453017066_mabdo3zBoLuYMKSqO8hMvHrblIO2VmwG.jpg);\n"
"    \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Budget_Export = QtWidgets.QPushButton(self.frame)
        self.Budget_Export.setMinimumSize(QtCore.QSize(200, 0))
        self.Budget_Export.setMaximumSize(QtCore.QSize(100, 35))
        self.Budget_Export.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.Budget_Export.setIconSize(QtCore.QSize(32, 32))
        self.Budget_Export.setObjectName("Budget_Export")
        self.gridLayout_2.addWidget(self.Budget_Export, 9, 1, 1, 1)
        self.Budget_amount = QtWidgets.QLineEdit(self.frame)
        self.Budget_amount.setMinimumSize(QtCore.QSize(0, 40))
        self.Budget_amount.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Budget_amount.setFont(font)
        self.Budget_amount.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.Budget_amount.setObjectName("Budget_amount")
        self.gridLayout_2.addWidget(self.Budget_amount, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 1, 1, 1)
        self.Budget_description = QtWidgets.QLineEdit(self.frame)
        self.Budget_description.setMinimumSize(QtCore.QSize(0, 40))
        self.Budget_description.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Budget_description.setFont(font)
        self.Budget_description.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.Budget_description.setObjectName("Budget_description")
        self.gridLayout_2.addWidget(self.Budget_description, 2, 1, 1, 1)
        self.Budget_Delete = QtWidgets.QPushButton(self.frame)
        self.Budget_Delete.setMinimumSize(QtCore.QSize(200, 0))
        self.Budget_Delete.setMaximumSize(QtCore.QSize(100, 35))
        self.Budget_Delete.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Budget_Delete.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.Budget_Delete.setIconSize(QtCore.QSize(32, 32))
        self.Budget_Delete.setObjectName("Budget_Delete")
        self.gridLayout_2.addWidget(self.Budget_Delete, 5, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 8, 1, 1, 1)
        self.Budget_AddBtn = QtWidgets.QPushButton(self.frame)
        self.Budget_AddBtn.setMinimumSize(QtCore.QSize(200, 0))
        self.Budget_AddBtn.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Budget_AddBtn.setFont(font)
        self.Budget_AddBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Budget_AddBtn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.Budget_AddBtn.setIconSize(QtCore.QSize(32, 32))
        self.Budget_AddBtn.setAutoRepeatDelay(200)
        self.Budget_AddBtn.setObjectName("Budget_AddBtn")
        self.gridLayout_2.addWidget(self.Budget_AddBtn, 4, 1, 1, 1)
        self.Budget_Save = QtWidgets.QPushButton(self.frame)
        self.Budget_Save.setMinimumSize(QtCore.QSize(200, 0))
        self.Budget_Save.setMaximumSize(QtCore.QSize(100, 35))
        self.Budget_Save.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Sidebar_Icons/Savew.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Budget_Save.setIcon(icon)
        self.Budget_Save.setIconSize(QtCore.QSize(32, 32))
        self.Budget_Save.setObjectName("Budget_Save")
        self.gridLayout_2.addWidget(self.Budget_Save, 7, 1, 1, 1)
        self.BD_combobox = QtWidgets.QComboBox(self.frame)
        self.BD_combobox.setStyleSheet("QComboBox{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"border-radius: 10px;}\n"
"")
        self.BD_combobox.setObjectName("BD_combobox")
        self.BD_combobox.addItem("")
        self.BD_combobox.addItem("")
        self.gridLayout_2.addWidget(self.BD_combobox, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 1, 2, 1)
        self.Budget_Table = QtWidgets.QTableWidget(self.frame_3)
        self.Budget_Table.setStyleSheet("QTableWidget{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QTableWidget:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.Budget_Table.setObjectName("Budget_Table")
        self.Budget_Table.setColumnCount(0)
        self.Budget_Table.setRowCount(0)
        self.Budget_Table.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.Budget_Table, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Budget_Export.setToolTip(_translate("Form", "Print to pdf"))
        self.Budget_Export.setText(_translate("Form", "Export"))
        self.Budget_Export.setShortcut(_translate("Form", "Ctrl+P"))
        self.Budget_amount.setPlaceholderText(_translate("Form", "Amount "))
        self.Budget_description.setPlaceholderText(_translate("Form", "Description"))
        self.Budget_Delete.setToolTip(_translate("Form", "Delte row"))
        self.Budget_Delete.setText(_translate("Form", "Delete"))
        self.Budget_Delete.setShortcut(_translate("Form", "Ctrl+D"))
        self.Budget_AddBtn.setToolTip(_translate("Form", "Add row"))
        self.Budget_AddBtn.setText(_translate("Form", "Add"))
        self.Budget_AddBtn.setShortcut(_translate("Form", "Ctrl+A"))
        self.Budget_Save.setToolTip(_translate("Form", "Save changes"))
        self.Budget_Save.setText(_translate("Form", " Save"))
        self.Budget_Save.setShortcut(_translate("Form", "Ctrl+S"))
        self.BD_combobox.setItemText(0, _translate("Form", "Deposit"))
        self.BD_combobox.setItemText(1, _translate("Form", "Withdraw"))
