# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'History.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(829, 651)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Purchase_Table_history = QtWidgets.QTableWidget(self.frame_3)
        self.Purchase_Table_history.setStyleSheet("QTableWidget{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QTableWidget:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.Purchase_Table_history.setObjectName("Purchase_Table_history")
        self.Purchase_Table_history.setColumnCount(0)
        self.Purchase_Table_history.setRowCount(0)
        self.Purchase_Table_history.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.Purchase_Table_history, 1, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Purchase_Export = QtWidgets.QPushButton(self.frame_4)
        self.Purchase_Export.setMinimumSize(QtCore.QSize(200, 0))
        self.Purchase_Export.setMaximumSize(QtCore.QSize(100, 35))
        self.Purchase_Export.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.Purchase_Export.setIconSize(QtCore.QSize(32, 32))
        self.Purchase_Export.setObjectName("Purchase_Export")
        self.gridLayout_5.addWidget(self.Purchase_Export, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_4, 2, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Sales_Export = QtWidgets.QPushButton(self.frame_2)
        self.Sales_Export.setMinimumSize(QtCore.QSize(200, 0))
        self.Sales_Export.setMaximumSize(QtCore.QSize(100, 35))
        self.Sales_Export.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.Sales_Export.setIconSize(QtCore.QSize(32, 32))
        self.Sales_Export.setObjectName("Sales_Export")
        self.gridLayout_3.addWidget(self.Sales_Export, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 2, 0, 1, 1)
        self.Sales_Table_history = QtWidgets.QTableWidget(self.frame_3)
        self.Sales_Table_history.setStyleSheet("QTableWidget{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QTableWidget:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.Sales_Table_history.setObjectName("Sales_Table_history")
        self.Sales_Table_history.setColumnCount(0)
        self.Sales_Table_history.setRowCount(0)
        self.Sales_Table_history.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.Sales_Table_history, 1, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setStyleSheet("background-color:rgb(100, 150, 200);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.label_2.setStyleSheet("QLabel{\n"
"\n"
"\n"
"background-color:rgb(100, 150, 200);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setMaximumSize(QtCore.QSize(250, 16777215))
        self.label.setStyleSheet("QLabel{\n"
"\n"
"\n"
"background-color:rgb(100, 150, 200);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_5, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Purchase_Export.setToolTip(_translate("Form", "Print to pdf"))
        self.Purchase_Export.setText(_translate("Form", "Export"))
        self.Purchase_Export.setShortcut(_translate("Form", "Ctrl+P"))
        self.Sales_Export.setToolTip(_translate("Form", "Print to pdf"))
        self.Sales_Export.setText(_translate("Form", "Export"))
        self.Sales_Export.setShortcut(_translate("Form", "Ctrl+P"))
        self.label_2.setWhatsThis(_translate("Form", "<html><head/><body><p align=\"center\">aaaa</p></body></html>"))
        self.label_2.setText(_translate("Form", "Purchase Recored History"))
        self.label.setWhatsThis(_translate("Form", "<html><head/><body><p align=\"center\">aaaa</p></body></html>"))
        self.label.setText(_translate("Form", "Sales Recored History"))
