# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_homw(object):
    def setupUi(self, homw):
        homw.setObjectName("homw")
        homw.resize(631, 546)
        self.gridLayout = QtWidgets.QGridLayout(homw)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(homw)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Purchase_History_Table = QtWidgets.QTableWidget(self.frame_2)
        self.Purchase_History_Table.setStyleSheet("QTableWidget{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QTableWidget:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.Purchase_History_Table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Purchase_History_Table.setObjectName("Purchase_History_Table")
        self.Purchase_History_Table.setColumnCount(0)
        self.Purchase_History_Table.setRowCount(0)
        self.Purchase_History_Table.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.Purchase_History_Table, 0, 0, 1, 1)
        self.Sales_History_Table = QtWidgets.QTableWidget(self.frame_2)
        self.Sales_History_Table.setStyleSheet("QTableWidget{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QTableWidget:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.Sales_History_Table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Sales_History_Table.setObjectName("Sales_History_Table")
        self.Sales_History_Table.setColumnCount(0)
        self.Sales_History_Table.setRowCount(0)
        self.Sales_History_Table.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.Sales_History_Table, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(homw)
        QtCore.QMetaObject.connectSlotsByName(homw)

    def retranslateUi(self, homw):
        _translate = QtCore.QCoreApplication.translate
        homw.setWindowTitle(_translate("homw", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    homw = QtWidgets.QWidget()
    ui = Ui_homw()
    ui.setupUi(homw)
    homw.show()
    sys.exit(app.exec_())
