# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Invoice.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Invoice(object):
    def setupUi(self, Invoice):
        Invoice.setObjectName("Invoice")
        Invoice.resize(1580, 1102)
        self.gridLayout = QtWidgets.QGridLayout(Invoice)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(Invoice)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.INV_searchBTN = QtWidgets.QPushButton(self.frame_3)
        self.INV_searchBTN.setMaximumSize(QtCore.QSize(40, 16777215))
        self.INV_searchBTN.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.INV_searchBTN.setFont(font)
        self.INV_searchBTN.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.INV_searchBTN.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Sidebar_Icons/icons8-search-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.INV_searchBTN.setIcon(icon)
        self.INV_searchBTN.setIconSize(QtCore.QSize(32, 32))
        self.INV_searchBTN.setAutoRepeatDelay(200)
        self.INV_searchBTN.setObjectName("INV_searchBTN")
        self.gridLayout_4.addWidget(self.INV_searchBTN, 0, 1, 1, 1)
        self.INV_Search_Bar = QtWidgets.QLineEdit(self.frame_3)
        self.INV_Search_Bar.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.INV_Search_Bar.setFont(font)
        self.INV_Search_Bar.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.INV_Search_Bar.setObjectName("INV_Search_Bar")
        self.gridLayout_4.addWidget(self.INV_Search_Bar, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame.setStyleSheet("QFrame{\n"
"background-image: url(:/newPrefix/مجلد جديد/360_F_453017066_mabdo3zBoLuYMKSqO8hMvHrblIO2VmwG.jpg);\n"
"    \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.INV_show_invoiceBTN = QtWidgets.QPushButton(self.frame)
        self.INV_show_invoiceBTN.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.INV_show_invoiceBTN.setObjectName("INV_show_invoiceBTN")
        self.gridLayout_2.addWidget(self.INV_show_invoiceBTN, 5, 1, 1, 1)
        self.INV_print = QtWidgets.QPushButton(self.frame)
        self.INV_print.setMinimumSize(QtCore.QSize(200, 0))
        self.INV_print.setMaximumSize(QtCore.QSize(100, 35))
        self.INV_print.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Sidebar_Icons/Printerw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.INV_print.setIcon(icon1)
        self.INV_print.setIconSize(QtCore.QSize(32, 32))
        self.INV_print.setObjectName("INV_print")
        self.gridLayout_2.addWidget(self.INV_print, 10, 1, 1, 1)
        self.INV_add = QtWidgets.QPushButton(self.frame)
        self.INV_add.setMinimumSize(QtCore.QSize(200, 0))
        self.INV_add.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.INV_add.setFont(font)
        self.INV_add.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.INV_add.setIconSize(QtCore.QSize(32, 32))
        self.INV_add.setAutoRepeatDelay(200)
        self.INV_add.setObjectName("INV_add")
        self.gridLayout_2.addWidget(self.INV_add, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 8, 1, 1, 1)
        self.INV_Edit = QtWidgets.QPushButton(self.frame)
        self.INV_Edit.setMinimumSize(QtCore.QSize(200, 0))
        self.INV_Edit.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.INV_Edit.setFont(font)
        self.INV_Edit.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Sidebar_Icons/Savew.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.INV_Edit.setIcon(icon2)
        self.INV_Edit.setIconSize(QtCore.QSize(32, 32))
        self.INV_Edit.setAutoRepeatDelay(200)
        self.INV_Edit.setObjectName("INV_Edit")
        self.gridLayout_2.addWidget(self.INV_Edit, 3, 1, 1, 1)
        self.INV_print_2 = QtWidgets.QPushButton(self.frame)
        self.INV_print_2.setMinimumSize(QtCore.QSize(200, 0))
        self.INV_print_2.setMaximumSize(QtCore.QSize(100, 35))
        self.INV_print_2.setToolTip("")
        self.INV_print_2.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.INV_print_2.setIconSize(QtCore.QSize(32, 32))
        self.INV_print_2.setObjectName("INV_print_2")
        self.gridLayout_2.addWidget(self.INV_print_2, 9, 1, 1, 1)
        self.INV_Delete = QtWidgets.QPushButton(self.frame)
        self.INV_Delete.setMinimumSize(QtCore.QSize(200, 0))
        self.INV_Delete.setMaximumSize(QtCore.QSize(100, 35))
        self.INV_Delete.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.INV_Delete.setIconSize(QtCore.QSize(32, 32))
        self.INV_Delete.setObjectName("INV_Delete")
        self.gridLayout_2.addWidget(self.INV_Delete, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 4, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 2, 3, 1)
        self.INV_TableWid = QtWidgets.QTableWidget(self.frame_3)
        self.INV_TableWid.setStyleSheet("QTableWidget{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QTableWidget:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")    
        self.INV_TableWid.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.INV_TableWid.setObjectName("INV_TableWid")
        self.INV_TableWid.setColumnCount(0)
        self.INV_TableWid.setRowCount(0)
        self.gridLayout_4.addWidget(self.INV_TableWid, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)

        self.retranslateUi(Invoice)
        QtCore.QMetaObject.connectSlotsByName(Invoice)
        Invoice.setTabOrder(self.INV_add, self.INV_Delete)
        Invoice.setTabOrder(self.INV_Delete, self.INV_Edit)
        Invoice.setTabOrder(self.INV_Edit, self.INV_show_invoiceBTN)
        Invoice.setTabOrder(self.INV_show_invoiceBTN, self.INV_print_2)
        Invoice.setTabOrder(self.INV_print_2, self.INV_print)
        Invoice.setTabOrder(self.INV_print, self.INV_Search_Bar)
        Invoice.setTabOrder(self.INV_Search_Bar, self.INV_searchBTN)
        Invoice.setTabOrder(self.INV_searchBTN, self.INV_TableWid)

    def retranslateUi(self, Invoice):
        _translate = QtCore.QCoreApplication.translate
        Invoice.setWindowTitle(_translate("Invoice", "Form"))
        self.INV_Search_Bar.setPlaceholderText(_translate("Invoice", "Search By Phone Number"))
        self.INV_show_invoiceBTN.setToolTip(_translate("Invoice", "(Alt+S)"))
        self.INV_show_invoiceBTN.setText(_translate("Invoice", "Show Invoice"))
        self.INV_show_invoiceBTN.setShortcut(_translate("Invoice", "Alt+S"))
        self.INV_print.setToolTip(_translate("Invoice", "Print invoice (Ctrl+P)"))
        self.INV_print.setText(_translate("Invoice", "Print"))
        self.INV_print.setShortcut(_translate("Invoice", "Ctrl+P"))
        self.INV_add.setToolTip(_translate("Invoice", "Add row (Alt+A)"))
        self.INV_add.setText(_translate("Invoice", "Add"))
        self.INV_add.setShortcut(_translate("Invoice", "Alt+A"))
        self.INV_Edit.setToolTip(_translate("Invoice", "Save Changes (Ctrl+S)"))
        self.INV_Edit.setText(_translate("Invoice", "Save"))
        self.INV_Edit.setShortcut(_translate("Invoice", "Ctrl+S"))
        self.INV_print_2.setText(_translate("Invoice", "Export"))
        self.INV_Delete.setToolTip(_translate("Invoice", "Delete row (Ctrl+D)"))
        self.INV_Delete.setText(_translate("Invoice", "Delete"))
        self.INV_Delete.setShortcut(_translate("Invoice", "Ctrl+D"))

