# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Products.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(883, 767)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame.setStyleSheet("QFrame{\n"
"background-image: url(:/newPrefix/مجلد جديد/360_F_453017066_mabdo3zBoLuYMKSqO8hMvHrblIO2VmwG.jpg);\n"
"    \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.product_PriceLineEdit = QtWidgets.QLineEdit(self.frame)
        self.product_PriceLineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.product_PriceLineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.product_PriceLineEdit.setFont(font)
        self.product_PriceLineEdit.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.product_PriceLineEdit.setObjectName("product_PriceLineEdit")
        self.gridLayout_2.addWidget(self.product_PriceLineEdit, 4, 1, 1, 1)
        self.product_print = QtWidgets.QPushButton(self.frame)
        self.product_print.setMinimumSize(QtCore.QSize(200, 0))
        self.product_print.setMaximumSize(QtCore.QSize(100, 35))
        self.product_print.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Sidebar_Icons/Printerw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.product_print.setIcon(icon)
        self.product_print.setIconSize(QtCore.QSize(32, 32))
        self.product_print.setObjectName("product_print")
        self.gridLayout_2.addWidget(self.product_print, 13, 1, 1, 1)
        self.product_Delete = QtWidgets.QPushButton(self.frame)
        self.product_Delete.setMinimumSize(QtCore.QSize(200, 0))
        self.product_Delete.setMaximumSize(QtCore.QSize(100, 35))
        self.product_Delete.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.product_Delete.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.product_Delete.setIconSize(QtCore.QSize(32, 32))
        self.product_Delete.setObjectName("product_Delete")
        self.gridLayout_2.addWidget(self.product_Delete, 8, 1, 1, 1)
        self.product_Name = QtWidgets.QLineEdit(self.frame)
        self.product_Name.setMinimumSize(QtCore.QSize(0, 40))
        self.product_Name.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.product_Name.setFont(font)
        self.product_Name.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.product_Name.setObjectName("product_Name")
        self.gridLayout_2.addWidget(self.product_Name, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 11, 1, 1, 1)
        self.product_QuantityLineEdit = QtWidgets.QLineEdit(self.frame)
        self.product_QuantityLineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.product_QuantityLineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.product_QuantityLineEdit.setFont(font)
        self.product_QuantityLineEdit.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.product_QuantityLineEdit.setObjectName("product_QuantityLineEdit")
        self.gridLayout_2.addWidget(self.product_QuantityLineEdit, 5, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 6, 1, 1, 1)
        self.product_AddBtn = QtWidgets.QPushButton(self.frame)
        self.product_AddBtn.setMinimumSize(QtCore.QSize(200, 0))
        self.product_AddBtn.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.product_AddBtn.setFont(font)
        self.product_AddBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.product_AddBtn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.product_AddBtn.setIconSize(QtCore.QSize(32, 32))
        self.product_AddBtn.setAutoRepeatDelay(200)
        self.product_AddBtn.setObjectName("product_AddBtn")
        self.gridLayout_2.addWidget(self.product_AddBtn, 7, 1, 1, 1)
        self.product_Save = QtWidgets.QPushButton(self.frame)
        self.product_Save.setMinimumSize(QtCore.QSize(200, 0))
        self.product_Save.setMaximumSize(QtCore.QSize(100, 35))
        self.product_Save.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Sidebar_Icons/Savew.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.product_Save.setIcon(icon1)
        self.product_Save.setIconSize(QtCore.QSize(32, 32))
        self.product_Save.setObjectName("product_Save")
        self.gridLayout_2.addWidget(self.product_Save, 10, 1, 1, 1)
        self.product_Export = QtWidgets.QPushButton(self.frame)
        self.product_Export.setMinimumSize(QtCore.QSize(200, 0))
        self.product_Export.setMaximumSize(QtCore.QSize(100, 35))
        self.product_Export.setToolTip("")
        self.product_Export.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.product_Export.setIconSize(QtCore.QSize(32, 32))
        self.product_Export.setObjectName("product_Export")
        self.gridLayout_2.addWidget(self.product_Export, 12, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 2, 2, 1)
        self.product_Table = QtWidgets.QTableWidget(self.frame_3)
        self.product_Table.setStyleSheet("QTableWidget{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QTableWidget:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.product_Table.setObjectName("product_Table")
        self.product_Table.setColumnCount(0)
        self.product_Table.setRowCount(0)
        self.gridLayout_4.addWidget(self.product_Table, 1, 0, 1, 1)
        self.product_Search_Bar = QtWidgets.QLineEdit(self.frame_3)
        self.product_Search_Bar.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.product_Search_Bar.setFont(font)
        self.product_Search_Bar.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.product_Search_Bar.setObjectName("product_Search_Bar")
        self.gridLayout_4.addWidget(self.product_Search_Bar, 0, 0, 1, 1)
        self.product_sreachBTN = QtWidgets.QPushButton(self.frame_3)
        self.product_sreachBTN.setMaximumSize(QtCore.QSize(40, 16777215))
        self.product_sreachBTN.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.product_sreachBTN.setFont(font)
        self.product_sreachBTN.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.product_sreachBTN.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Sidebar_Icons/icons8-search-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.product_sreachBTN.setIcon(icon2)
        self.product_sreachBTN.setIconSize(QtCore.QSize(32, 32))
        self.product_sreachBTN.setAutoRepeatDelay(200)
        self.product_sreachBTN.setObjectName("product_sreachBTN")
        self.gridLayout_4.addWidget(self.product_sreachBTN, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.product_Name, self.product_PriceLineEdit)
        Form.setTabOrder(self.product_PriceLineEdit, self.product_QuantityLineEdit)
        Form.setTabOrder(self.product_QuantityLineEdit, self.product_AddBtn)
        Form.setTabOrder(self.product_AddBtn, self.product_Delete)
        Form.setTabOrder(self.product_Delete, self.product_Save)
        Form.setTabOrder(self.product_Save, self.product_Export)
        Form.setTabOrder(self.product_Export, self.product_print)
        Form.setTabOrder(self.product_print, self.product_Search_Bar)
        Form.setTabOrder(self.product_Search_Bar, self.product_sreachBTN)
        Form.setTabOrder(self.product_sreachBTN, self.product_Table)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.product_PriceLineEdit.setPlaceholderText(_translate("Form", "Base Price"))
        self.product_print.setToolTip(_translate("Form", "Print to pdf (Ctrl+P)"))
        self.product_print.setText(_translate("Form", "Print To PDF"))
        self.product_print.setShortcut(_translate("Form", "Ctrl+P"))
        self.product_Delete.setToolTip(_translate("Form", "Delte row (Ctrl+D)"))
        self.product_Delete.setText(_translate("Form", "Delete"))
        self.product_Delete.setShortcut(_translate("Form", "Ctrl+D"))
        self.product_Name.setPlaceholderText(_translate("Form", "Product Name"))
        self.product_QuantityLineEdit.setPlaceholderText(_translate("Form", "Quantity"))
        self.product_AddBtn.setToolTip(_translate("Form", "Add row (Alt+A)"))
        self.product_AddBtn.setText(_translate("Form", "Add"))
        self.product_AddBtn.setShortcut(_translate("Form", "Alt+A"))
        self.product_Save.setToolTip(_translate("Form", "Save changes (Ctrl+S)"))
        self.product_Save.setText(_translate("Form", " Save"))
        self.product_Save.setShortcut(_translate("Form", "Ctrl+S"))
        self.product_Export.setText(_translate("Form", "Export"))
        self.product_Search_Bar.setPlaceholderText(_translate("Form", "Search By description"))
