# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PurchaseW.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Purchase(object):
    def setupUi(self, Purchase):
        Purchase.setObjectName("Purchase")
        Purchase.resize(830, 558)
        self.gridLayout = QtWidgets.QGridLayout(Purchase)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(Purchase)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Purchase_Table = QtWidgets.QTableWidget(self.frame_3)
        self.Purchase_Table.setStyleSheet("QTableWidget{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QTableWidget:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.Purchase_Table.setObjectName("Purchase_Table")
        self.Purchase_Table.setColumnCount(0)
        self.Purchase_Table.setRowCount(0)
        self.Purchase_Table.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.Purchase_Table, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame.setStyleSheet("QFrame{\n"
"background-image: url(:/newPrefix/مجلد جديد/360_F_453017066_mabdo3zBoLuYMKSqO8hMvHrblIO2VmwG.jpg);\n"
"    \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Purchase_export = QtWidgets.QPushButton(self.frame)
        self.Purchase_export.setMinimumSize(QtCore.QSize(200, 0))
        self.Purchase_export.setMaximumSize(QtCore.QSize(100, 35))
        self.Purchase_export.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.Purchase_export.setIconSize(QtCore.QSize(32, 32))
        self.Purchase_export.setObjectName("Purchase_export")
        self.gridLayout_2.addWidget(self.Purchase_export, 8, 1, 1, 1)
        self.Purchase_print = QtWidgets.QPushButton(self.frame)
        self.Purchase_print.setMinimumSize(QtCore.QSize(200, 0))
        self.Purchase_print.setMaximumSize(QtCore.QSize(100, 35))
        self.Purchase_print.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Sidebar_Icons/Printerw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Purchase_print.setIcon(icon)
        self.Purchase_print.setIconSize(QtCore.QSize(32, 32))
        self.Purchase_print.setObjectName("Purchase_print")
        self.gridLayout_2.addWidget(self.Purchase_print, 9, 1, 1, 1)
        self.Purchase_Save = QtWidgets.QPushButton(self.frame)
        self.Purchase_Save.setMinimumSize(QtCore.QSize(200, 0))
        self.Purchase_Save.setMaximumSize(QtCore.QSize(100, 35))
        self.Purchase_Save.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Sidebar_Icons/Savew.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Purchase_Save.setIcon(icon1)
        self.Purchase_Save.setIconSize(QtCore.QSize(32, 32))
        self.Purchase_Save.setObjectName("Purchase_Save")
        self.gridLayout_2.addWidget(self.Purchase_Save, 6, 1, 1, 1)
        self.Purchase_AddBtn = QtWidgets.QPushButton(self.frame)
        self.Purchase_AddBtn.setMinimumSize(QtCore.QSize(200, 0))
        self.Purchase_AddBtn.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Purchase_AddBtn.setFont(font)
        self.Purchase_AddBtn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.Purchase_AddBtn.setIconSize(QtCore.QSize(32, 32))
        self.Purchase_AddBtn.setAutoRepeatDelay(200)
        self.Purchase_AddBtn.setObjectName("Purchase_AddBtn")
        self.gridLayout_2.addWidget(self.Purchase_AddBtn, 3, 1, 1, 1)
        self.Purchase_Delete = QtWidgets.QPushButton(self.frame)
        self.Purchase_Delete.setMinimumSize(QtCore.QSize(200, 0))
        self.Purchase_Delete.setMaximumSize(QtCore.QSize(100, 35))
        self.Purchase_Delete.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.Purchase_Delete.setIconSize(QtCore.QSize(32, 32))
        self.Purchase_Delete.setObjectName("Purchase_Delete")
        self.gridLayout_2.addWidget(self.Purchase_Delete, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 7, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 2, 2, 1)
        self.Purchase_Search_Bar = QtWidgets.QLineEdit(self.frame_3)
        self.Purchase_Search_Bar.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Purchase_Search_Bar.setFont(font)
        self.Purchase_Search_Bar.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.Purchase_Search_Bar.setObjectName("Purchase_Search_Bar")
        self.gridLayout_4.addWidget(self.Purchase_Search_Bar, 0, 0, 1, 1)
        self.Purchase_sreachBTN = QtWidgets.QPushButton(self.frame_3)
        self.Purchase_sreachBTN.setMaximumSize(QtCore.QSize(40, 16777215))
        self.Purchase_sreachBTN.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Purchase_sreachBTN.setFont(font)
        self.Purchase_sreachBTN.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.Purchase_sreachBTN.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Sidebar_Icons/icons8-search-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Purchase_sreachBTN.setIcon(icon2)
        self.Purchase_sreachBTN.setIconSize(QtCore.QSize(32, 32))
        self.Purchase_sreachBTN.setAutoRepeatDelay(200)
        self.Purchase_sreachBTN.setObjectName("Purchase_sreachBTN")
        self.gridLayout_4.addWidget(self.Purchase_sreachBTN, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)

        self.retranslateUi(Purchase)
        QtCore.QMetaObject.connectSlotsByName(Purchase)

    def retranslateUi(self, Purchase):
        _translate = QtCore.QCoreApplication.translate
        Purchase.setWindowTitle(_translate("Purchase", "Form"))
        self.Purchase_export.setToolTip(_translate("Purchase", "Print to pdf"))
        self.Purchase_export.setText(_translate("Purchase", "Export"))
        self.Purchase_print.setToolTip(_translate("Purchase", "Print to pdf"))
        self.Purchase_print.setText(_translate("Purchase", "Print To PDF"))
        self.Purchase_Save.setToolTip(_translate("Purchase", "Save changes"))
        self.Purchase_Save.setText(_translate("Purchase", " Save"))
        self.Purchase_AddBtn.setToolTip(_translate("Purchase", "Add row"))
        self.Purchase_AddBtn.setText(_translate("Purchase", "Add"))
        self.Purchase_Delete.setToolTip(_translate("Purchase", "Delete row"))
        self.Purchase_Delete.setText(_translate("Purchase", "Delete"))
        self.Purchase_Search_Bar.setPlaceholderText(_translate("Purchase", "Search By Phone Number"))

