# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Purchase_record.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(943, 696)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame.setStyleSheet("QFrame{\n"
"background-image: url(:/newPrefix/مجلد جديد/360_F_453017066_mabdo3zBoLuYMKSqO8hMvHrblIO2VmwG.jpg);\n"
"    \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.PR_Add = QtWidgets.QPushButton(self.frame)
        self.PR_Add.setMinimumSize(QtCore.QSize(200, 0))
        self.PR_Add.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PR_Add.setFont(font)
        self.PR_Add.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.PR_Add.setIconSize(QtCore.QSize(32, 32))
        self.PR_Add.setAutoRepeatDelay(200)
        self.PR_Add.setObjectName("PR_Add")
        self.gridLayout_2.addWidget(self.PR_Add, 6, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 12, 1, 1, 1)
        self.PR_Done = QtWidgets.QPushButton(self.frame)
        self.PR_Done.setMinimumSize(QtCore.QSize(200, 0))
        self.PR_Done.setMaximumSize(QtCore.QSize(100, 35))
        self.PR_Done.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.PR_Done.setIconSize(QtCore.QSize(32, 32))
        self.PR_Done.setObjectName("PR_Done")
        self.gridLayout_2.addWidget(self.PR_Done, 13, 1, 1, 1)
        self.PR_ProductID = QtWidgets.QLineEdit(self.frame)
        self.PR_ProductID.setMinimumSize(QtCore.QSize(0, 40))
        self.PR_ProductID.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PR_ProductID.setFont(font)
        self.PR_ProductID.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.PR_ProductID.setObjectName("PR_ProductID")
        self.gridLayout_2.addWidget(self.PR_ProductID, 1, 1, 1, 1)
        self.PR_Description = QtWidgets.QLineEdit(self.frame)
        self.PR_Description.setMinimumSize(QtCore.QSize(0, 40))
        self.PR_Description.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PR_Description.setFont(font)
        self.PR_Description.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.PR_Description.setObjectName("PR_Description")
        self.gridLayout_2.addWidget(self.PR_Description, 4, 1, 1, 1)
        self.PR_PhoneNumber = QtWidgets.QLineEdit(self.frame)
        self.PR_PhoneNumber.setMinimumSize(QtCore.QSize(0, 40))
        self.PR_PhoneNumber.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PR_PhoneNumber.setFont(font)
        self.PR_PhoneNumber.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.PR_PhoneNumber.setObjectName("PR_PhoneNumber")
        self.gridLayout_2.addWidget(self.PR_PhoneNumber, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 5, 1, 1, 1)
        self.PR_Quantity = QtWidgets.QLineEdit(self.frame)
        self.PR_Quantity.setMinimumSize(QtCore.QSize(0, 40))
        self.PR_Quantity.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PR_Quantity.setFont(font)
        self.PR_Quantity.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.PR_Quantity.setObjectName("PR_Quantity")
        self.gridLayout_2.addWidget(self.PR_Quantity, 3, 1, 1, 1)
        self.PR_Delete = QtWidgets.QPushButton(self.frame)
        self.PR_Delete.setMinimumSize(QtCore.QSize(200, 0))
        self.PR_Delete.setMaximumSize(QtCore.QSize(100, 35))
        self.PR_Delete.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.PR_Delete.setIconSize(QtCore.QSize(32, 32))
        self.PR_Delete.setObjectName("PR_Delete")
        self.gridLayout_2.addWidget(self.PR_Delete, 7, 1, 1, 1)
        self.PR_Save = QtWidgets.QPushButton(self.frame)
        self.PR_Save.setMinimumSize(QtCore.QSize(200, 0))
        self.PR_Save.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PR_Save.setFont(font)
        self.PR_Save.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Sidebar_Icons/Savew.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PR_Save.setIcon(icon)
        self.PR_Save.setIconSize(QtCore.QSize(32, 32))
        self.PR_Save.setAutoRepeatDelay(200)
        self.PR_Save.setObjectName("PR_Save")
        self.gridLayout_2.addWidget(self.PR_Save, 8, 1, 1, 1)
        self.PR_Price = QtWidgets.QLineEdit(self.frame)
        self.PR_Price.setMinimumSize(QtCore.QSize(0, 40))
        self.PR_Price.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PR_Price.setFont(font)
        self.PR_Price.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.PR_Price.setObjectName("PR_Price")
        self.gridLayout_2.addWidget(self.PR_Price, 2, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 1, 1, 1)
        self.PR_table = QtWidgets.QTableWidget(self.frame_3)
        self.PR_table.setStyleSheet("QTableWidget{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QTableWidget:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.PR_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.PR_table.setObjectName("PR_table")
        self.PR_table.setColumnCount(0)
        self.PR_table.setRowCount(0)
        self.PR_table.horizontalHeader().setVisible(True)
        self.PR_table.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.PR_table, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.PR_PhoneNumber, self.PR_ProductID)
        Form.setTabOrder(self.PR_ProductID, self.PR_Quantity)
        Form.setTabOrder(self.PR_Quantity, self.PR_Description)
        Form.setTabOrder(self.PR_Description, self.PR_Add)
        Form.setTabOrder(self.PR_Add, self.PR_Delete)
        Form.setTabOrder(self.PR_Delete, self.PR_Save)
        Form.setTabOrder(self.PR_Save, self.PR_Done)
        Form.setTabOrder(self.PR_Done, self.PR_table)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.PR_Add.setToolTip(_translate("Form", "Add row (Alt+A)"))
        self.PR_Add.setText(_translate("Form", "ADD"))
        self.PR_Add.setShortcut(_translate("Form", "Alt+A"))
        self.PR_Done.setToolTip(_translate("Form", "(Alt+D)"))
        self.PR_Done.setText(_translate("Form", "Done"))
        self.PR_Done.setShortcut(_translate("Form", "Alt+D"))
        self.PR_ProductID.setPlaceholderText(_translate("Form", "Product ID"))
        self.PR_Description.setPlaceholderText(_translate("Form", "Description"))
        self.PR_PhoneNumber.setPlaceholderText(_translate("Form", "Phone Number"))
        self.PR_Quantity.setPlaceholderText(_translate("Form", "Quantity"))
        self.PR_Delete.setToolTip(_translate("Form", "Delete row (Ctrl+D)"))
        self.PR_Delete.setText(_translate("Form", "DELETE"))
        self.PR_Delete.setShortcut(_translate("Form", "Ctrl+D"))
        self.PR_Save.setToolTip(_translate("Form", "Save Changes (Ctrl+S)"))
        self.PR_Save.setText(_translate("Form", "Save"))
        self.PR_Save.setShortcut(_translate("Form", "Ctrl+S"))
        self.PR_Price.setPlaceholderText(_translate("Form", "Product ID"))
