# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SalesRecords.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SalesRocrods(object):
    def setupUi(self, SalesRocrods):
        SalesRocrods.setObjectName("SalesRocrods")
        SalesRocrods.resize(969, 669)
        self.gridLayout = QtWidgets.QGridLayout(SalesRocrods)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(SalesRocrods)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame.setStyleSheet("QFrame{\n"
"background-image: url(:/newPrefix/مجلد جديد/360_F_453017066_mabdo3zBoLuYMKSqO8hMvHrblIO2VmwG.jpg);\n"
"    \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.SR_ProductID = QtWidgets.QLineEdit(self.frame)
        self.SR_ProductID.setMinimumSize(QtCore.QSize(0, 40))
        self.SR_ProductID.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.SR_ProductID.setFont(font)
        self.SR_ProductID.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.SR_ProductID.setObjectName("SR_ProductID")
        self.gridLayout_2.addWidget(self.SR_ProductID, 1, 1, 1, 1)
        self.SR_Quantity = QtWidgets.QLineEdit(self.frame)
        self.SR_Quantity.setMinimumSize(QtCore.QSize(0, 40))
        self.SR_Quantity.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.SR_Quantity.setFont(font)
        self.SR_Quantity.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.SR_Quantity.setObjectName("SR_Quantity")
        self.gridLayout_2.addWidget(self.SR_Quantity, 2, 1, 1, 1)
        self.SR_save = QtWidgets.QPushButton(self.frame)
        self.SR_save.setMinimumSize(QtCore.QSize(200, 0))
        self.SR_save.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.SR_save.setFont(font)
        self.SR_save.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.SR_save.setIconSize(QtCore.QSize(32, 32))
        self.SR_save.setAutoRepeatDelay(200)
        self.SR_save.setObjectName("SR_save")
        self.gridLayout_2.addWidget(self.SR_save, 7, 1, 1, 1)
        self.SR_add = QtWidgets.QPushButton(self.frame)
        self.SR_add.setMinimumSize(QtCore.QSize(200, 0))
        self.SR_add.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.SR_add.setFont(font)
        self.SR_add.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.SR_add.setIconSize(QtCore.QSize(32, 32))
        self.SR_add.setAutoRepeatDelay(200)
        self.SR_add.setObjectName("SR_add")
        self.gridLayout_2.addWidget(self.SR_add, 6, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 11, 1, 1, 1)
        self.SR_Delete = QtWidgets.QPushButton(self.frame)
        self.SR_Delete.setMinimumSize(QtCore.QSize(200, 0))
        self.SR_Delete.setMaximumSize(QtCore.QSize(100, 35))
        self.SR_Delete.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.SR_Delete.setIconSize(QtCore.QSize(32, 32))
        self.SR_Delete.setObjectName("SR_Delete")
        self.gridLayout_2.addWidget(self.SR_Delete, 8, 1, 1, 1)
        self.SR_Discount = QtWidgets.QLineEdit(self.frame)
        self.SR_Discount.setMinimumSize(QtCore.QSize(0, 40))
        self.SR_Discount.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.SR_Discount.setFont(font)
        self.SR_Discount.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.SR_Discount.setObjectName("SR_Discount")
        self.gridLayout_2.addWidget(self.SR_Discount, 4, 1, 1, 1)
        self.SR_Description = QtWidgets.QLineEdit(self.frame)
        self.SR_Description.setMinimumSize(QtCore.QSize(0, 40))
        self.SR_Description.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.SR_Description.setFont(font)
        self.SR_Description.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.SR_Description.setObjectName("SR_Description")
        self.gridLayout_2.addWidget(self.SR_Description, 3, 1, 1, 1)
        self.SR_Done = QtWidgets.QPushButton(self.frame)
        self.SR_Done.setMinimumSize(QtCore.QSize(200, 0))
        self.SR_Done.setMaximumSize(QtCore.QSize(100, 35))
        self.SR_Done.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.SR_Done.setIconSize(QtCore.QSize(32, 32))
        self.SR_Done.setObjectName("SR_Done")
        self.gridLayout_2.addWidget(self.SR_Done, 12, 1, 1, 1)
        self.SR_PhoneNumber = QtWidgets.QLineEdit(self.frame)
        self.SR_PhoneNumber.setMinimumSize(QtCore.QSize(0, 40))
        self.SR_PhoneNumber.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.SR_PhoneNumber.setFont(font)
        self.SR_PhoneNumber.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.SR_PhoneNumber.setObjectName("SR_PhoneNumber")
        self.gridLayout_2.addWidget(self.SR_PhoneNumber, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 5, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 1, 1, 1)
        self.SR_table = QtWidgets.QTableWidget(self.frame_3)
        self.SR_table.setStyleSheet("QTableWidget{\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid #62D5FF;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QTableWidget:focus{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"    \n"
"    \n"
"    border:2px solid rgb(255, 167, 72);\n"
"}")
        self.SR_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.SR_table.setObjectName("SR_table")
        self.SR_table.setColumnCount(0)
        self.SR_table.setRowCount(0)
        self.SR_table.horizontalHeader().setVisible(True)
        self.SR_table.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.SR_table, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)

        self.retranslateUi(SalesRocrods)
        QtCore.QMetaObject.connectSlotsByName(SalesRocrods)

    def retranslateUi(self, SalesRocrods):
        _translate = QtCore.QCoreApplication.translate
        SalesRocrods.setWindowTitle(_translate("SalesRocrods", "Form"))
        self.SR_ProductID.setPlaceholderText(_translate("SalesRocrods", "Product ID"))
        self.SR_Quantity.setPlaceholderText(_translate("SalesRocrods", "Quantity"))
        self.SR_save.setText(_translate("SalesRocrods", "Save"))
        self.SR_add.setText(_translate("SalesRocrods", "ADD"))
        self.SR_Delete.setText(_translate("SalesRocrods", "DELETE"))
        self.SR_Discount.setPlaceholderText(_translate("SalesRocrods", "Discount"))
        self.SR_Description.setPlaceholderText(_translate("SalesRocrods", "Description"))
        self.SR_Done.setText(_translate("SalesRocrods", "Done"))
        self.SR_PhoneNumber.setPlaceholderText(_translate("SalesRocrods", "Phone Number"))
