# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sidebar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(246, 881)
        Form.setMinimumSize(QtCore.QSize(0, 500))
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.mainframe = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainframe.sizePolicy().hasHeightForWidth())
        self.mainframe.setSizePolicy(sizePolicy)
        self.mainframe.setMinimumSize(QtCore.QSize(200, 500))
        self.mainframe.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mainframe.setStyleSheet("\n"
"background-color:rgba(15, 76, 117, 255);\n"
"\n"
"")
        self.mainframe.setObjectName("mainframe")
        self.gridLayout = QtWidgets.QGridLayout(self.mainframe)
        self.gridLayout.setContentsMargins(2, 17, 3, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.SalesRecordsBTN = QtWidgets.QPushButton(self.mainframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SalesRecordsBTN.sizePolicy().hasHeightForWidth())
        self.SalesRecordsBTN.setSizePolicy(sizePolicy)
        self.SalesRecordsBTN.setMaximumSize(QtCore.QSize(200, 100))
        self.SalesRecordsBTN.setStyleSheet("QPushButton:Pressed { background-color: rgb(0, 0, 127); border:4px;  }\n"
"\n"
"QPushButton { color: rgb(255, 255, 255); border-style: none; min-height: 1.5em; font: 15pt \"Yu Gothic UI\"; padding-left: 5px; text-align:left;\n"
"\n"
"\n"
"border: 2px ;\n"
"border-radius: 1px;\n"
"\n"
"\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt }    QPushButton:hover { background-color: rgb(59, 116, 191); }  QPushButton:checked { border: 2px solid rgba(255, 255, 255, 255); border-style: solid; border-color:rgba(255, 255, 255, 255); border-style: solid; padding: 7px; }\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Sidebar_Icons/Cartw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SalesRecordsBTN.setIcon(icon)
        self.SalesRecordsBTN.setIconSize(QtCore.QSize(32, 32))
        self.SalesRecordsBTN.setCheckable(True)
        self.SalesRecordsBTN.setAutoExclusive(True)
        self.SalesRecordsBTN.setObjectName("SalesRecordsBTN")
        self.gridLayout.addWidget(self.SalesRecordsBTN, 2, 0, 1, 1)
        self.Product_Btn = QtWidgets.QPushButton(self.mainframe)
        self.Product_Btn.setMaximumSize(QtCore.QSize(200, 100))
        self.Product_Btn.setStyleSheet("QPushButton:Pressed { background-color: rgb(0, 0, 127); border:4px;  }\n"
"\n"
"QPushButton { color: rgb(255, 255, 255); border-style: none; min-height: 1.5em; font: 15pt \"Yu Gothic UI\"; padding-left: 5px; text-align:left;\n"
"\n"
"\n"
"border: 2px ;\n"
"border-radius: 1px;\n"
"\n"
"\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt }    QPushButton:hover { background-color: rgb(59, 116, 191); }  QPushButton:checked { border: 2px solid rgba(255, 255, 255, 255); border-style: solid; border-color:rgba(255, 255, 255, 255); border-style: solid; padding: 7px; }\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Sidebar_Icons/Productsw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Product_Btn.setIcon(icon1)
        self.Product_Btn.setIconSize(QtCore.QSize(32, 32))
        self.Product_Btn.setCheckable(True)
        self.Product_Btn.setAutoExclusive(True)
        self.Product_Btn.setObjectName("Product_Btn")
        self.gridLayout.addWidget(self.Product_Btn, 7, 0, 1, 1)
        self.Customer = QtWidgets.QPushButton(self.mainframe)
        self.Customer.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Customer.setFont(font)
        self.Customer.setStyleSheet("QPushButton:Pressed { background-color: rgb(0, 0, 127); border:4px;  }\n"
"\n"
"QPushButton { color: rgb(255, 255, 255); border-style: none; min-height: 1.5em; font: 15pt \"Yu Gothic UI\"; padding-left: 5px; text-align:left;\n"
"\n"
"\n"
"border: 2px ;\n"
"border-radius: 1px;\n"
"\n"
"\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt }    QPushButton:hover { background-color: rgb(59, 116, 191); }  QPushButton:checked { border: 2px solid rgba(255, 255, 255, 255); border-style: solid; border-color:rgba(255, 255, 255, 255); border-style: solid; padding: 7px; }\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Sidebar_Icons/Customerw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Customer.setIcon(icon2)
        self.Customer.setIconSize(QtCore.QSize(32, 32))
        self.Customer.setCheckable(True)
        self.Customer.setAutoExclusive(True)
        self.Customer.setObjectName("Customer")
        self.gridLayout.addWidget(self.Customer, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(17, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.PurchaseBtn = QtWidgets.QPushButton(self.mainframe)
        self.PurchaseBtn.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PurchaseBtn.setFont(font)
        self.PurchaseBtn.setStyleSheet("QPushButton:Pressed { background-color: rgb(0, 0, 127); border:4px;  }\n"
"\n"
"QPushButton { color: rgb(255, 255, 255); border-style: none; min-height: 1.5em; font: 15pt \"Yu Gothic UI\"; padding-left: 5px; text-align:left;\n"
"\n"
"\n"
"border: 2px ;\n"
"border-radius: 1px;\n"
"\n"
"\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt }    QPushButton:hover { background-color: rgb(59, 116, 191); }  QPushButton:checked { border: 2px solid rgba(255, 255, 255, 255); border-style: solid; border-color:rgba(255, 255, 255, 255); border-style: solid; padding: 7px; }\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Sidebar_Icons/distribution.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PurchaseBtn.setIcon(icon3)
        self.PurchaseBtn.setIconSize(QtCore.QSize(32, 32))
        self.PurchaseBtn.setCheckable(True)
        self.PurchaseBtn.setAutoExclusive(True)
        self.PurchaseBtn.setAutoRepeatDelay(200)
        self.PurchaseBtn.setObjectName("PurchaseBtn")
        self.gridLayout.addWidget(self.PurchaseBtn, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 500, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 10, 0, 1, 1)
        self.HomeBtn = QtWidgets.QPushButton(self.mainframe)
        self.HomeBtn.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.HomeBtn.setFont(font)
        self.HomeBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.HomeBtn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.HomeBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Sidebar_Icons/Homee.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HomeBtn.setIcon(icon4)
        self.HomeBtn.setIconSize(QtCore.QSize(32, 32))
        self.HomeBtn.setCheckable(True)
        self.HomeBtn.setChecked(True)
        self.HomeBtn.setAutoExclusive(True)
        self.HomeBtn.setAutoRepeatDelay(200)
        self.HomeBtn.setObjectName("HomeBtn")
        self.gridLayout.addWidget(self.HomeBtn, 0, 0, 1, 1)
        self.Show_supplier = QtWidgets.QPushButton(self.mainframe)
        self.Show_supplier.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Show_supplier.setFont(font)
        self.Show_supplier.setStyleSheet("QPushButton:Pressed { background-color: rgb(0, 0, 127); border:4px;  }\n"
"\n"
"QPushButton { color: rgb(255, 255, 255); border-style: none; min-height: 1.5em; font: 15pt \"Yu Gothic UI\"; padding-left: 5px; text-align:left;\n"
"\n"
"\n"
"border: 2px ;\n"
"border-radius: 1px;\n"
"\n"
"\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt }    QPushButton:hover { background-color: rgb(59, 116, 191); }  QPushButton:checked { border: 2px solid rgba(255, 255, 255, 255); border-style: solid; border-color:rgba(255, 255, 255, 255); border-style: solid; padding: 7px; }\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Sidebar_Icons/Supplierw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Show_supplier.setIcon(icon5)
        self.Show_supplier.setIconSize(QtCore.QSize(32, 32))
        self.Show_supplier.setCheckable(True)
        self.Show_supplier.setAutoExclusive(True)
        self.Show_supplier.setObjectName("Show_supplier")
        self.gridLayout.addWidget(self.Show_supplier, 5, 0, 1, 1)
        self.Budget_BTN = QtWidgets.QPushButton(self.mainframe)
        self.Budget_BTN.setMaximumSize(QtCore.QSize(200, 100))
        self.Budget_BTN.setStyleSheet("QPushButton:Pressed { background-color: rgb(0, 0, 127); border:4px;  }\n"
"\n"
"QPushButton { color: rgb(255, 255, 255); border-style: none; min-height: 1.5em; font: 15pt \"Yu Gothic UI\"; padding-left: 5px; text-align:left;\n"
"\n"
"\n"
"border: 2px ;\n"
"border-radius: 1px;\n"
"\n"
"\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt }    QPushButton:hover { background-color: rgb(59, 116, 191); }  QPushButton:checked { border: 2px solid rgba(255, 255, 255, 255); border-style: solid; border-color:rgba(255, 255, 255, 255); border-style: solid; padding: 7px; }\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Sidebar_Icons/Sales1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Budget_BTN.setIcon(icon6)
        self.Budget_BTN.setIconSize(QtCore.QSize(32, 32))
        self.Budget_BTN.setCheckable(True)
        self.Budget_BTN.setAutoExclusive(True)
        self.Budget_BTN.setObjectName("Budget_BTN")
        self.gridLayout.addWidget(self.Budget_BTN, 8, 0, 1, 1)
        self.History_BTN = QtWidgets.QPushButton(self.mainframe)
        self.History_BTN.setMaximumSize(QtCore.QSize(200, 100))
        self.History_BTN.setStyleSheet("QPushButton:Pressed { background-color: rgb(0, 0, 127); border:4px;  }\n"
"\n"
"QPushButton { color: rgb(255, 255, 255); border-style: none; min-height: 1.5em; font: 15pt \"Yu Gothic UI\"; padding-left: 5px; text-align:left;\n"
"\n"
"\n"
"border: 2px ;\n"
"border-radius: 1px;\n"
"\n"
"\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt }    QPushButton:hover { background-color: rgb(59, 116, 191); }  QPushButton:checked { border: 2px solid rgba(255, 255, 255, 255); border-style: solid; border-color:rgba(255, 255, 255, 255); border-style: solid; padding: 7px; }\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Sidebar_Icons/history.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.History_BTN.setIcon(icon7)
        self.History_BTN.setIconSize(QtCore.QSize(32, 32))
        self.History_BTN.setCheckable(True)
        self.History_BTN.setAutoExclusive(True)
        self.History_BTN.setObjectName("History_BTN")
        self.gridLayout.addWidget(self.History_BTN, 9, 0, 1, 1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mainframe)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.SalesRecordsBTN.setToolTip(_translate("Form", "Sales invoices"))
        self.SalesRecordsBTN.setText(_translate("Form", "Sales Invoices"))
        self.Product_Btn.setToolTip(_translate("Form", "Product list"))
        self.Product_Btn.setText(_translate("Form", "Products"))
        self.Customer.setToolTip(_translate("Form", "Customer list"))
        self.Customer.setText(_translate("Form", "Customer"))
        self.PurchaseBtn.setToolTip(_translate("Form", "Purchase a product"))
        self.PurchaseBtn.setText(_translate("Form", "Purchase Invoice"))
        self.HomeBtn.setToolTip(_translate("Form", "Home "))
        self.Show_supplier.setToolTip(_translate("Form", "Supplier list"))
        self.Show_supplier.setText(_translate("Form", "Supplier"))
        self.Budget_BTN.setToolTip(_translate("Form", "Product list"))
        self.Budget_BTN.setText(_translate("Form", "Budget Account"))
        self.History_BTN.setToolTip(_translate("Form", "Product list"))
        self.History_BTN.setText(_translate("Form", "History"))
