# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'You_Sure.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(366, 270)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(16777215, 45))
        self.label.setStyleSheet("QLabel{\n"
"\n"
"\n"
"\n"
"\n"
"background-color: rgb(220,220, 220);\n"
"\n"
"\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border:2px solid  rgb(255, 57, 60);\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.IM_Sure_BTN = QtWidgets.QPushButton(self.frame)
        self.IM_Sure_BTN.setMinimumSize(QtCore.QSize(200, 0))
        self.IM_Sure_BTN.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.IM_Sure_BTN.setFont(font)
        self.IM_Sure_BTN.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.IM_Sure_BTN.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.IM_Sure_BTN.setIconSize(QtCore.QSize(32, 32))
        self.IM_Sure_BTN.setAutoRepeatDelay(200)
        self.IM_Sure_BTN.setObjectName("IM_Sure_BTN")
        self.gridLayout_2.addWidget(self.IM_Sure_BTN, 1, 0, 1, 1)
        self.Cancel_BTN = QtWidgets.QPushButton(self.frame)
        self.Cancel_BTN.setMinimumSize(QtCore.QSize(200, 0))
        self.Cancel_BTN.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Cancel_BTN.setFont(font)
        self.Cancel_BTN.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Cancel_BTN.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"background-color: rgba(15, 76, 117, 255);\n"
"font: \"Sitka Heading\";\n"
"padding: 3px;\n"
"border: 2px ;\n"
"border-radius: 10px;\n"
"font: bold 15px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgba(21, 113, 174,255);\n"
"    border: 2px solid rgba(255, 255, 255, 255)\n"
"\n"
"\n"
"}")
        self.Cancel_BTN.setIconSize(QtCore.QSize(32, 32))
        self.Cancel_BTN.setAutoRepeatDelay(200)
        self.Cancel_BTN.setObjectName("Cancel_BTN")
        self.gridLayout_2.addWidget(self.Cancel_BTN, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Are You Sure?..."))
        self.IM_Sure_BTN.setToolTip(_translate("Form", "Add row"))
        self.IM_Sure_BTN.setText(_translate("Form", "I Am Sure"))
        self.IM_Sure_BTN.setShortcut(_translate("Form", "Ctrl+A"))
        self.Cancel_BTN.setToolTip(_translate("Form", "Add row"))
        self.Cancel_BTN.setText(_translate("Form", "Cancel"))
        self.Cancel_BTN.setShortcut(_translate("Form", "Ctrl+A"))
